name: CI

on:
  workflow_dispatch:

  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Microsoft.PowerShell.PSResourceGet -Repository PSGallery

      - name: Setup GitHub repository
        shell: pwsh
        run: Set-PSResourceRepository GitHub -Uri https://nuget.pkg.github.com/sontarru/index.json -Trusted

      - name: Publish modules
        shell: pwsh
        run: ./Publish.ps1 -ApiKey $env:APIKEY
        env:
          APIKEY: ${{secrets.GITHUB_TOKEN}}
